### ISSUE TITLE
Build error in standalone Python wrappers

### ISSUE THREAD

**Issue by GiadaFallo** [lamyj/sycomore#1]
I am trying to compile the git version of the code, because I would like to use the new _off_resonance_ method, which is not in the released version. 

After starting the `python setup.py install` I receive the following error (after 80%):
```
epg/simd_api.txx:285:57: error: implicit instantiation of undefined template 'xsimd::batch<std::__1::complex<double>, 4>'
    auto const simd_end = states_count - states_count % Batch::size;
```

Note that if I build the library with `cmake` command (as suggested in the documentation) it seems to build the library. Should I use this builded version in my python code? 

**System configuration**

- Operating system: MACOS
- Sycomore version: the one in the master branch (not yet released)
- Python version: 3.7.3
- Compiler version: Clang version 12.0.0

**Comment by lamyj** [comment]
The discrepancy between using `setup.py` and `cmake` is a bit weird: compiling with cmake should cause the same error as with `setup.py`. Do you have still have the cmake output?

Anyhow, the latest commits have added an extra dependency to [xsimd](https://github.com/xtensor-stack/xsimd) to get SIMD operations on all EPG models, yielding quite a large speedup. I have not yet updated the README for this, but xsimd is rather simple to install: you can follow their instructions (basically clone and follow the usual cmake route), or run what I'm using in the macOS CI (https://github.com/lamyj/sycomore/blob/master/.ci/brew/install#L33-L37) from the root directory of sycomore.

All the off-resonance stuff is a bit experimental. If you have some examples to validate the results, I'll be glad to have a look at them.

**Comment by GiadaFallo** [comment]
This is the output after executing cmake and make from the build directory:

```
[ 29%] Built target libsycomore
[ 30%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/Array.cpp.o
[ 32%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/Dimensions.cpp.o
[ 33%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/Grid.cpp.o
[ 34%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/GridScanner.cpp.o
[ 36%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/HardPulseApproximation.cpp.o
[ 37%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/Pulse.cpp.o
[ 38%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/Quantity.cpp.o
[ 40%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/Species.cpp.o
[ 41%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/TimeInterval.cpp.o
[ 42%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/como/Model.cpp.o
[ 44%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/como/como.cpp.o
[ 45%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/epg/Discrete.cpp.o
[ 46%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/epg/Discrete3D.cpp.o
[ 48%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/epg/Regular.cpp.o
[ 49%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/epg/epg.cpp.o
[ 50%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/magnetization.cpp.o
[ 52%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/sycomore.cpp.o
[ 53%] Building CXX object wrappers/python/CMakeFiles/pysycomore.dir/units.cpp.o
[ 54%] Linking CXX shared library _sycomore.so
[ 54%] Built target pysycomore
[ 57%] Built target test_off_resonance
[ 60%] Built target test_epg_Discrete3D
[ 62%] Built target test_magnetization
[ 65%] Built target test_Array
[ 68%] Built target test_Pulse
[ 70%] Built target test_Species
[ 73%] Built target test_epg_Discrete
[ 76%] Built target test_GridScanner
[ 78%] Built target test_epg_Regular
[ 81%] Built target test_TimeInterval
[ 84%] Built target test_Dimensions
[ 86%] Built target test_Grid
[ 89%] Built target test_Quantity
[ 92%] Built target test_pulse_profile
[ 94%] Built target test_GRE
[ 97%] Built target test_como_Model
[100%] Built target test_Units
```

It seems good. I have already installed the _xsimd_ dependency, but I tried again with your instructions. I obtain the same error when I try to run the setup.py. 

Yes, If I will be able to build the library, I will surely share our results. And we will eventually help with the testing of this experimental implementation.

**Comment by lamyj** [comment]
Latest commit (154096b) should solve this issue with setup.py. Can you retry and confirm?

**Comment by GiadaFallo** [comment]
Yes, it's working!
